### ISSUE TITLE
Issue with route and directory separator

### ISSUE THREAD

**Issue by Thiktak** [bastinald/laravel-livewire-routes#2]
Hello,

First thanks for all the work you are doing here.
I tried to play a little bit with your ui repository, and it worked well. After I had discovered that the project have been archived, I tried to update my local work ... and I got an an error with the route bundle.

Linked to your fix 41ce8663d15103df31bc10807a1f5b4a10cac379

Indeed, you are playing with paths & realpath function, and then this is sensible about windows/linux directory separators.
Going back to the DIRECTORY_SEPARATOR fix the issue.

```php
        $component = $namespace . str_replace(
                ['/', '.php'],
                ['\\', ''],
                Str::after($component->getRealPath(), realpath(app_path()) . DIRECTORY_SEPARATOR)
            );
```

**Issue:**
Install fresh laravel, and install bastinald/laravel-livewire-ui. No route found (no Welcome, nor Home)
System: Windows & XAMPP

**Fix:**
Use DIRECTORY_SEPARATOR (rollback).

**Comment by bastinald** [comment]
Hi, I re-added `DIRECTORY_SEPARATOR` in the latest release. Please composer update and it should work now.
